### ISSUE TITLE
block discovery doesn't account for parens, etc., in strings

### ISSUE THREAD

**Issue by clukey** [jasongilman/proto-repl#1]
An example from exercism.io (slightly modified to fit in the editor width):

``` clojure
(def fawls (= "" "("))
```

In the preceding code, if the cursor is at the beginning of the block and the `proto-repl:execute-block` command is sent, proto-repl is unable to find the end of the block, and if the cursor is at the end of the block, proto-repl identifies the block as:

``` clojure
(= "" "("))
```

and evaluates the expression as false, but does not define fawls.

Loving the package otherwise!

**Comment by jasongilman** [comment]
Thanks for letting me know about the issue.

**Comment by jasongilman** [comment]
Bug fix is released with 0.2.2 version.
