### ISSUE TITLE
Colors for exception stacktraces

### ISSUE THREAD

**Issue by naartjie** [jasongilman/proto-repl#100]
Hi. Thank you sooooooo much for this project!! I have just started using it today.

When I see exception stacktraces in the repl, the color codes don't seem to be getting interpreted (I am seeing colors in other places). Is this something specific to my setup (i.e. some leaked settings from my shell config?), or is it like this for everyone? Do I need another package installed? I have installed Ink already, but I don't think Ink can help here.

<img width="543" alt="screen shot 2016-05-06 at 15 18 53" src="https://cloud.githubusercontent.com/assets/514563/15074279/55c68ad8-139e-11e6-8359-ed1a85f29cd7.png">

**Comment by jasongilman** [comment]
The colors that you see are built into Atom. It's parsing the REPL contents as Clojure and performing syntax highlighting. You want to avoid having color codes printed in the Atom REPL. My guess is that you have some plugin for your project either in the project.clj or in ~/.lein/profiles.clj that tries to add the color coding. I've heard of plugins that try to do that so the REPL at the command line will have colors but you don't need that within Atom. If you can disable that it should fix the problem.

**Comment by naartjie** [comment]
@jasongilman thanks so much. I can confirm I had [`[venantius/ultra "0.4.0"]`](https://github.com/venantius/ultra) as one of my plugins in `profiles.clj`.
