### ISSUE TITLE
Repl tab enhancements - class and open in a tab instead of split

### ISSUE THREAD

**Issue by mauricioszabo** [jasongilman/proto-repl#102]
Hello. I would like to propose some cosmetic changes that I believe are very simple.

First, that the Repl class would have a specific `class` attribute - something like `proto-repl`, so I could style the repl (so, when seeing test results and other things, I could change font size), or I would be able to bind keybindings that would only work on Repl.

Second, that we add an option to open repl on a tab, instead of split.

Third, that we show notifications when the repl finished refreshing namespace code, or connection with nrepl is stablished or dropped, so I wouldn't need to keep the repl open just to see these things.

Thanks for the great project!

**Comment by jasongilman** [comment]
The first two requests seem reasonable. For the third one how were you thinking the notifications should be displayed? The REPL window needs to be kept open (at least for now) but can be in the background. Atom provides a notifications API. You can try it by bringing up the developer tools (cmd-alt-i on mac) and pasting in `atom.notifications.addSuccess("Refreshing complete")`. That will popup a message that will disappear in about 5 seconds.

I could see some people finding the notifications annoying but I'm interested in trying them.

**Comment by jasongilman** [comment]
I didn't change the notifications as part of this as I wasn't sure about making that one yet. I did the other two changes. The editor class is `proto-repl-repl`

**Comment by mauricioszabo** [comment]
Okay, so I would like to suggest a kinda simple change: I'm working on some REPL integrations and I though it would be great if I could have an API to subscribe to some events, like when the REPL was connected, when it was disconnected, after a refresh, etc.

This would eliminate the notification need - anyone could subscribe to the events and do whatever they want. WDYT?

**Comment by jasongilman** [comment]
I think that's a great idea. I like adding additional extension points in Proto REPL. Would you mind filling a new issue for this?
