### ISSUE TITLE
Offline use

### ISSUE THREAD

**Issue by tiagodalloca** [jasongilman/proto-repl#108]
Is it possible to use it offline?
Is there any possibilities of make it default, like a new feature?

**Comment by jasongilman** [comment]
What do you mean by offline? It doesn't attempt to connect to the Internet at all during normal use.

**Comment by tiagodalloca** [comment]
Yes, I know. I mean without any connection at all, even when starting up the repl.

**Comment by jasongilman** [comment]
Can you expand on that? What doesn't work when you're offline? Do you have a stack trace or error message?

**Comment by jasongilman** [comment]
The only two things I can think of with this issue are:
1. Using without an internet connection. This works fine with the exception that downloading maven libraries won't work but that's to be expected.
2. Using it without having to start up a new JVM instance. That is possible through use of the self hosted repl. You can start that up by following these instructions: https://github.com/jasongilman/proto-repl#starting-a-self-hosted-clojurescript-repl

If you have any more details on a problem or use case please comment here.
