### ISSUE TITLE
"Refresh Warning: IllegalArgumentException No such namespace: clojure.tools.namespace.repl" when toggling REPL in a Leiningen project directory

### ISSUE THREAD

**Issue by WalterGR** [jasongilman/proto-repl#111]
I'm using Atom 1.7.3 and proto-repl 1.1.0.

`lein version` shows

```
Leiningen 2.5.3 on Java 1.6.0_65 Java HotSpot(TM) 64-Bit Server VM
```

`lein repl` shows:

```
REPL-y 0.3.7, nREPL 0.2.10
Clojure 1.7.0
Java HotSpot(TM) 64-Bit Server VM 1.6.0_65-b14-466.1-11M4716
```

I have a Leiningen project I last worked on in January.  When I start Atom from that project directory, and do `proto-repl:toggle`, the following is printed in the REPL:

```
Starting REPL with lein in /Users/walter/test
nREPL server started on port 54559 on host 127.0.0.1 - nrepl://127.0.0.1:54559
user=>
Refreshing code...
No user namespace defined. Defaulting to clojure.tools.namespace.repl/refresh.

clojure.tools.namespace.repl not available. Add as a dependency to allow refresh.
Refresh Warning: IllegalArgumentException No such namespace: clojure.tools.namespace.repl  clojure.lang.Var.find (Var.java:141)
--------------------
```

Evaluating simple things (e.g. `(+ 1 2)`) works.  I haven't tried evaluating anything complex.

When I start Atom in a directory that isn't a Leiningen project and do `proto-repl:toggle`, I don't experience any errors.

**Comment by jasongilman** [comment]
This is because your project doesn't include clojure.tools.namespace.repl as a dependency. You should add the [proto-repl](https://clojars.org/proto-repl) library as a dependency and you'll get the refresh support plus a whole lot more. 

I'm going to treat this issue as a sign that the error message here should be more explicit about what to do to correct the problem.

**Comment by WalterGR** [comment]
> I'm going to treat this issue as a sign that the error message here should be more explicit about what to do to correct the problem.

That sounds good.

**Comment by dl1ely** [comment]
Adding proto-repl as dependency did not solve that for me, i had to add `[org.clojure/tools.namespace "0.2.11"]` to get rid of the error message.

**Comment by jasongilman** [comment]
I updated the error message. It will be in the next release of proto repl plugin. I updated the Proto REPL library so that clojure tools.namespace would automatically be included without having to explicitly add that.

**Comment by JamesMcMahon** [comment]
FYI, I'm actually still seeing this error message so I wonder if you missed a case,

> Refresh Warning: IllegalArgumentException No such namespace: clojure.tools.namespace.repl  clojure.lang.Var.find (Var.java:141)

Adding [proto-repl](https://clojars.org/proto-repl) as a dependency cleared it up.
