### ISSUE TITLE
Start REPL with env vars

### ISSUE THREAD

**Issue by lamuria** [jasongilman/proto-repl#118]
Hi,

I have a project that have some env dependencies, db, services and stuff like that.. We have been adding that kind of dependencies thru env vars. So on terminal when we start the repl we start with those vars.

question: with proto-repl is it possible to start the repl with some env vars?

**Comment by jasongilman** [comment]
Can you show an example of how you start the REPL now at the command line with env vars? I'd imagine you wouldn't type them in every time. I'd imagine you'd put them in a file.

It's possible depending on the way you set them that they're already available. Run this in the REPL to see if they are `(keys (System/getenv))`

One thing that comes to mind would be to change the leiningen command in the proto repl settings to your own script that would set the environment variables and then call `lein repl :headless` at the end.

**Comment by lamuria** [comment]
Yes, I have all the vars in a file and I start the repl like this: `forego run -e config/production.env lein repl`

yeah.. that seems to be a good solution. 👍 but how can I do that?

**Comment by lamuria** [comment]
Yes, I have all the vars in a file and I start the repl like this: `forego run -e config/production.env lein repl`

yeah.. that seems to be a good solution. 👍 but how can I do that? is it the Lein Args field?

the command that I put there was `forego run -e config/production.env lein repl :headless`

but I got an error `'forego' is not a task. See 'lein help'.` it seems that the whole command is prefixed by lein.. can you help here?

**Comment by jasongilman** [comment]
I couldn't figure out a way to do this in Proto REPL without adding it as a special feature. One thing you could do would be to modify the lein script to set the environment variables. Would that work for you?

**Comment by lamuria** [comment]
thanks @jasongilman that would work for me.
