### ISSUE TITLE
Be able to pass various flags to Boot

### ISSUE THREAD

**Issue by mikebelanger** [jasongilman/proto-repl#120]
Proto REPL is looking pretty rad, but I'm more into using Boot these days, and AFAIK, there's no way of invoking the REPL with Boot's various sub-tasks (ie like: `boot dev`, for now it looks like it's just `boot repl`.

Is there any way of adding a new boot flag to the current Proto REPL?

**Comment by jasongilman** [comment]
Under Proto REPL settings you can specify settings for what to pass to boot. Is this what you were looking for?

<img width="773" alt="settings_ __users_jason_work_github_workspace_proto-repl-charts" src="https://cloud.githubusercontent.com/assets/192983/16750166/bdb06e9c-479d-11e6-9e42-1d903ceb66e2.png">

**Comment by mikebelanger** [comment]
It does, thank-you!  Although I could've sworn the settings button went away, similar to this old (but closed) issue : https://github.com/atom/settings-view/issues/573.  Maybe I just spaced.
