### ISSUE TITLE
expecting proto-repl toggle to recognize project.clj

### ISSUE THREAD

**Issue by carocad** [jasongilman/proto-repl#122]
Hey @jasongilman,

I am not sure if this is a bug or if it is the intended behavior. 

I was expecting the `proto-repl: toggle` command to recognize that I am inside a project an use the `project.clj` file to start the repl. Nevertheless I found myself surprised when proto-repl simply started a `proto-repl/proto-no-proj`, the default proto-repl leiningen project.

On the other hand if I do `right click -> proto-repl -> start repl from open project.clj` then it recognizes the project.clj in my filepath and starts a repl with it.

Is there any way to change that?

**Comment by jasongilman** [comment]
Where is the project.clj in the hierarchy? It should find it automatically if it's at the root of the folder you opened. It may be having trouble if it's in a different location.

**Comment by carocad** [comment]
it is a normal leiningen project. The project.clj is located at the root of the file from which I started proto-repl. I might be wrong but I think that this was not the case with the previous version of proto-repl (in atom) that I was using (just a hunch though). You can even check the hierarchie of you wish here: https://github.com/carocad/clemence

**Comment by carocad** [comment]
I am closing this as the bug suddenly stopped happening. It was maybe because I had both normal atom and `atom --dev` running while testing my changes on proto-repl. I can't reproduce this anymore with a normal atom execution.
