### ISSUE TITLE
display error-results underline

### ISSUE THREAD

**Issue by carocad** [jasongilman/proto-repl#124]
This is just for the record (I will do this, no worries).
Since exceptions' causes can get quite long(wide?) I think it would be better to display them underline to use all the space of the editor. That would help make them more readable.

Unfortunately, ink has a bug which render underline elements as result not as errors, see JunoLab/atom-ink#64. Once it lands I can submit a PR to change it in proto-repl

**Comment by carocad** [comment]
@jasongilman There is already a patch on atom-ink which should fix the issue. Nevertheless there no release yet of that atom-ink version.
I could send you the PR now or if you prefer we could make it only when there is a new ink release.

As you prefer ;)

**Comment by jasongilman** [comment]
I didn't understand originally what this was fixing. This sounds like a
great fix. I'm not in a hurry to get it so I'm ok waiting. That said if
it's a small easy pull request feel free and I'll do a patch release of
proto repl.
