### ISSUE TITLE
Stop reset the namespace

### ISSUE THREAD

**Issue by MasterMastic** [jasongilman/proto-repl#133]
The REPL keeps changing the namespace to the "user" namespace by itself after evaluating certain things (that should not change it, of course). I'm not sure if it necessarily resets it to "user" or to its default.
I haven't dug around this yet to see when exactly it happens but is it a known issue? it's been bugging me (pun not intended) ever since I started using it. If it's not then I'll start digging around and provide more information.

**Comment by MasterMastic** [comment]
Found an easy use-case; `def` something and the namespace resets.

```
nREPL server started on port 53280 on host 127.0.0.1 - nrepl://127.0.0.1:53280
user=>
Refreshing code...
:reloading (user)
Default Proto REPL Leiningen project started
Refresh complete
(ns my.ns)
my.ns=>
nil
*ns*
my.ns=>
[clojure.lang.Namespace 1068098879 "my.ns"]
(def x 5)
user=>
#'user/x
*ns*
user=>
[clojure.lang.Namespace 1133979038 "user"]
```

**Comment by jasongilman** [comment]
Thanks for the example. I thought you were referring to a different behavior. There must be problem tracking the current namespace in the REPL class. I'll take a look when I get a chance to see if I can fix it.

**Comment by jgrimes** [comment]
The workaround in my PR fixes this, though I can imagine that some commands should be able to change the REPL's namespace. Even in those cases the fact that it has changed should probably be printed out, so maybe this fixes it for good?
