### ISSUE TITLE
Auto scroll does not (always) work with the ink console

### ISSUE THREAD

**Issue by moxaj** [jasongilman/proto-repl#140]
If I send

```
(+ 1 2)
```

to the console (with `ctrl-comma-b`), it automatically scrolls to the bottom. However, if I send

```
(+
  1
  2)
```

it no longer does. 

Once the console isn't scrolled to the bottom, it seems to remain that way until I manually scroll.

**Comment by jasongilman** [comment]
This is an Atom ink issue (see link above) and they have a pull request open to fix it.
