### ISSUE TITLE
Feature request: support ANSI colour codes in the repl

### ISSUE THREAD

**Issue by alza-bitz** [jasongilman/proto-repl#149]
It would be great if proto-repl could support this.

**Comment by carocad** [comment]
There is already a PR on atom-ink to support this feature on the console. Once it lands, proto-repl would support it automatically on its ink-console.

https://github.com/JunoLab/atom-ink/pull/68

**Comment by jasongilman** [comment]
Closing this since it's covered by a future Atom ink change.
