### ISSUE TITLE
Proto-repl does not start `Error starting repl: Error: spawn lein ENOENT`

### ISSUE THREAD

**Issue by bcambel** [jasongilman/proto-repl#150]
I am currently having this issue with Proto-repl version 1.4.2 on MacOSX El-Capitan on Atom 1.9.8

```
Error starting repl: Error: spawn lein ENOENT
You may need to configure the lein path in proto-repl settings
REPL Closed
```

Thanks,
Bahadir

**Comment by jasongilman** [comment]
Have you configured the lein path in proto repl settings? If not you need to bring up the settings and configure that. 

Instructions from the README:
Modify "Lein Path" to the path where Leiningen was installed. Use `which lein` in a terminal to get the path.
This should be something like `/some/path/bin/lein`

**Comment by bcambel** [comment]
Hey @jasongilman 
After I setup the lein path, updated to version 1.4.3, everything is good! thnx.
