### ISSUE TITLE
Can not load ns when ns with meta

### ISSUE THREAD

**Issue by jnriver** [jasongilman/proto-repl#152]
When ns with meta like

```
(ns ^{:doc "foo"
         :author "f@oo.com"}
    foo.bar)
```

Can not load namespace correctly, `open-file-containing-var` `Autocompletion` are both disable.

Remove the meta

```
(ns foo.bar)
```

Everything is OK.

**Comment by jasongilman** [comment]
Thanks for filing the issue. This is a duplicate of #104. I think @qwtel was working on a fix here, https://github.com/jasongilman/proto-repl/pull/151, but he closed it. I'll take a look if he doesn't resolve it.

**Comment by qwtel** [comment]
I don't think those two are related. Also, sending the above command to the repl works for me.

**Comment by jnriver** [comment]
I met this problem when working at a clj file whose ns has meta.

When this file's ns has meta, I can't use `open-file-containing-var` and `Autocompletion` at this file. Other files are OK. Remove meta, everything is OK.

**Comment by jasongilman** [comment]
Yeah this is definitely a different issue. I'm not sure what I was thinking. I think I know how to improve the parsing as well.

**Comment by mauricioszabo** [comment]
There's a way to make it work that's relatively easy - we can use EditorUtils to get all top-level blocks, find the one that it's a `ns` declaration, then use `parseEdn` - this will remove the meta.

I can work around on this if this is the right way of doing, WDYT?

**Comment by jasongilman** [comment]
That's a great idea. This has been a long term annoying problem and it would be great to get it resolved.
