### ISSUE TITLE
Ratios displaying as float

### ISSUE THREAD

**Issue by russellpipal** [jasongilman/proto-repl#158]
I'm new to Clojure development, but ratios don't seem to be working properly in my proto-repl. In lein, 1/2 returns 1/2, but in proto-repl 1/2 returns 0.5.

**Comment by carocad** [comment]
this is a duplicate of #77

**Comment by jasongilman** [comment]
Check out the details on #77 to understand why it's happening. You can disable automatic pretty printing to stop that in the REPL.
