### ISSUE TITLE
Ability to pass environment variables to lein

### ISSUE THREAD

**Issue by alza-bitz** [jasongilman/proto-repl#162]
Hi there,

It would be great if there was a setting to specify environment variables that would be passed to Leiningen for the repl, e.g. `MIDJE_COLORIZE`.

background: the project I'm working on uses Midje, and unfortunately 1) Midje doesn't appear to implement the logic needed to disable ANSI color when the output is not a terminal, and 2) Atom Ink doesn't have a release yet with ANSI color support included. As such, I'm finding the test output hard to read in the REPL.

Thanks :)

**Comment by carocad** [comment]
@alzadude 
atom-ink v0.5.1 should already support ansi-colors on their console. (see [commit](https://github.com/JunoLab/atom-ink/commit/799d7d41a1deaee949995dcc5ce231b04d46e8e9))

If this is what you were looking for then please update atom-ink and close this issue :)

**Comment by alza-bitz** [comment]
Hi there, 

Yes I noticed that ANSI colors were suddenly working when I updated atom-ink :)

So, I'll close this issue now..

Thanks :)
