### ISSUE TITLE
Can't copy execution output from REPL

### ISSUE THREAD

**Issue by rahulthewall** [jasongilman/proto-repl#163]
Hi,

Earlier, I was able to execute my Clojure functions and then copy the result from REPL. I can't seem to do this with the latest update. Can you please bring back this functionality?

proto-repl version: 1.4.7

**Comment by torbjornvatn** [comment]
I have this problem too!

**Comment by jasongilman** [comment]
Here's a quick workaround until I or someone else is able to fix the problem. After you execute something at the REPL that you want to copy and paste pretty print the result. The pretty printed version is copyable. You can either use the keybinding to pretty print or the toolbar button.

**Comment by rahulthewall** [comment]
Another quick workaround is to not use the `ink console`.

**Comment by jasongilman** [comment]
This has been fixed in the latest released Proto REPL version.

**Comment by kurtharriger** [comment]
Hmm I seem to be having some issues with special characters in the copied text:

If I start a self hosted repl then define a literal map something like follows
```
> {:a "asf" :b "adf"}
```
it spits back out the result which looks basically as expected

```
{:b "adf", :a "asf"}
```

Now copy the result from proto-repl
Then in a terminal window I started a plain clojurescript repl
rlwrap lein cljsbuild repl-rhino 
and paste the result
```
cljs.user=> {:b "adf", :a "asf"}
```
This is what I get back
```
WARNING: Use of undeclared Var cljs.user/ :a  at line 1 <cljs repl>
{:b\u00A0 "adf", nil "asf"}
```


I had copied some output from the repl into my code and was fighting weird syntax errors I was unable to visually identify.  It appears the \u00A0 is a &nbsp; which seems to be introduced in the formatting of the output in electron but creates some problems if just copied and pasted litterally
