### ISSUE TITLE
Possible problem with lein-runner.coffee

### ISSUE THREAD

**Issue by pedro-w** [jasongilman/proto-repl#166]
I encountered a problem with running proto-repl on Windows. I will file that as a separate issue (#167). My trouble was made worse because I think there is also an issue with lein-runner.coffee.

If the `childProcess.spawn` call on line 26 fails and throws, it's caught on line 55 with a call to `processData`. But that function is not defined until line 38. I saw errors in the developer console of Atom saying that `processData` is not a function. As a result the thrown error is never seen.

I am not a coffeescript expert but I believe the definition of `processData` should be moved up, possibly before the `try` on line 11.

Thanks for your support.

Using Atom 1.10.2 with proto-repl 1.4.7.

**Comment by jasongilman** [comment]
Thanks for the bug report and the detailed explanation. I've been very busy with work recently and haven't had time to look at these issues. I'll get to this within the next week. 

Proto REPL has worked on Windows in the past. It should still work but there may be a regression.

**Comment by pedro-w** [comment]
Thanks for getting back to me!

> Proto REPL has worked on Windows in the past.

Definitely. I've used it myself only a few months ago and it was fine. It may be something in Atom itself; it is still changing at a rapid pace.
