### ISSUE TITLE
Allow connecting to an existing nREPL port

### ISSUE THREAD

**Issue by jasongilman** [jasongilman/proto-repl#17]
Proto REPL now uses nREPL as the backend but it still expects to start up the REPL itself. It should support an additional way of starting the REPL by connecting to a specified REPL host and port. This will need to display some kind of prompt to allow the user to enter the host and port number.

**Comment by jasongilman** [comment]
The [go-to-line](https://github.com/atom/go-to-line/blob/master/lib/go-to-line-view.coffee) package prompts for user input to type in a line number. A similar approach can be taken to prompt for host and port.

**Comment by carloscarcamo** [comment]
+1
