### ISSUE TITLE
Support keyboard layouts other than QWERTY

### ISSUE THREAD

**Issue by allentiak** [jasongilman/proto-repl#170]
I normally switch across two layouts: US-Intl and Colemak.
When using the Colemak layout, proto-repl's keybindings don't work. The same keybindings do work properly when using the QWERTY layout.
I thought it was a problem related with (the lack of) the `keyboard-localization` package (which is supposedly already into 1.11x). However, I have experienced this bug in both Atom 1.10.2 and 1.11b5.
This is the only plugin that gives me this problem.

**Comment by jasongilman** [comment]
Can you enable the keybinding resolver in Atom and see what the keys resolve to when using Colemak? When you enable the keybinding resolver it will show what the keys resolve to and the precedence.  Here's an example where I pressed enter in a Clojure file:

<img width="1439" alt="user_clj_ __users_jason_work_github_workspace_proto-repl-charts" src="https://cloud.githubusercontent.com/assets/192983/19017732/c137c532-8812-11e6-8842-0c75451472ab.png">

**Comment by allentiak** [comment]
Hi, sorry for the delay.

This turns out being quite interesting...

Both in Atom 1.11b5 and in Atom 1.10.2 (with package `keyboard-localization` enabled):
When using US-International (basically, US with dead keys), "Ctrl+Alt+´ (a dead key)" gets resolved to "Ctrl+Alt+ä", whereas "Ctrl+Alt+; (not a dead key)" gets resolved to "Ctrl+Alt+ü".
When in Colemak, "Ctrl+Alt+´ (not a dead key)" gets resolved to "Ctrl+Alt+ä", whereas "Ctrl+Alt+; (not a dead key)" does not get successfully resolved; I only get "Ctrl+Alt".

**Comment by allentiak** [comment]
Good news!
I see some improvements with Atom's new versions:

With Atom 1.11.1, I see a small improvement:
When using US-International (basically, US with dead keys), both "Ctrl+Alt+´ (a dead key)" and "Ctrl+Alt+; (not a dead key)" get correctly resolved.
When using Colemak, whereas "Ctrl+Alt+´ (a dead key)" gets correctly resolved, "Ctrl+Alt+; (not a dead key)" get incorrectly resolved to "Ctrl+Alt".

With Atom Beta 1.12b1, both combinations get correctly resolved in both layouts.

Even though I don't know how to close this ticket by saying "solved in Atom 1.12beta1", as it now works, I just closed it :-)
