### ISSUE TITLE
Go to symbol definition ?

### ISSUE THREAD

**Issue by didibus** [jasongilman/proto-repl#172]
Is there a way in proto-repl to go to a symbol's definition?

**Comment by jasongilman** [comment]
Yes there is. See "proto-repl:open-file-containing-var" in the keybindings https://github.com/jasongilman/proto-repl/blob/master/README.md#keybindings-and-events

And example in the demo https://github.com/jasongilman/proto-repl-demo/blob/master/demos.md#demo-open-namespace-or-var-definition

**Comment by didibus** [comment]
It doesn't seem to ever work for me, I either get a Unable to resolve var error, or it opens a file which is empty, or it throws a NullPointerException.

**Comment by jasongilman** [comment]
Did you try opening the proto REPL demo project? It should work with that.

**Comment by pedro-w** [comment]
I can confirm it doesn't work for me either. Trying to get a var's definition it opens an empty file.
From the REPL tab I can see (for example) it's looking to open `/C:/Users/Pedrow/clojure/project/src/project/net.clj` which should not have that leading slash.

This is on Windows, atom 1.11.2.

**Comment by didibus** [comment]
I am on Windows too, so could be a windows related issue.

**Comment by pedro-w** [comment]
As a suggestion, in proto-repl.coffee:694 you have

``` clojure
file-path (.getPath (.getResource (clojure.lang.RT/baseLoader) file))
```

I've tested this to work on Windows and it ought to be cross-platform too:

``` clojure
url (.getResource (clojure.lang.RT/baseLoader) file)
file-path (.getAbsolutePath (clojure.java.io/as-file url))
```

**Comment by pedro-w** [comment]
Actually what I put in my previous comment is OK for files _within_ the project but fails for symbols defined in jar files (e.g. Error trying to open: IllegalArgumentException Not a file: jar:file:/... ) - more thought needed!

**Comment by didibus** [comment]
The NullPointerException happens if you try to do open file containing Var on a var that is not namespace qualified.
