### ISSUE TITLE
Start REPL in Windows "cannot find the path specified"

### ISSUE THREAD

**Issue by pbwolf** [jasongilman/proto-repl#178]
Using the menu, Packages > proto-repl > Start REPL, produces a Console tab with a lot of blue REPL instructions followed by this:

```
Starting REPL with lein in C:\Users\you\.atom\packages/proto-repl/proto-no-proj
The system cannot find the path specified.
REPL Closed
```

I pasted the filename onto the end of a DIR command in a terminal window, corrected the path segment separators to a backslash, and it was there.  I suppose the path segment separators might be the problem.

**Comment by pbwolf** [comment]
Oops.  Although "lein" works in a command window, it evidently is not sufficient for Proto-Repl.  I changed it to "lein.bat" in Proto-Repl settings and now the Proto-Repl REPL opens correctly.  So this could be regarded as an enhancement request.

**Comment by nigelgilbert** [comment]
@pbwolf Fixed my issue.

**Comment by rohitvvv** [comment]
@pbwolf Helped me as well. Thanks

**Comment by gjonor** [comment]
@pbwolf Fixed it for me, too. I tried to paste the full path to lein.bat first, but that did not work. The error message in the console is not very helpful unfortunately.

**Comment by Hamido-san** [comment]
So why is this issue "closed"? Do we expect every single newcomer to discover this workaround on their own?
