### ISSUE TITLE
Autocompletion stops working once REPL is started

### ISSUE THREAD

**Issue by tosh** [jasongilman/proto-repl#187]
I did not have the `[proto-repl "0.3.1"]` expressed as dependency in my `project.clj` file.

This way the autocompletion (powered by Atom?) works until I start the REPL. Once the REPL starts there is no autocompletion anymore. I then read through the README and found the recommendation to add proto-repl as dependency to my project and now (better?) autocompletion works once I've started the REPL.

I don't know if this is wanted/expected behaviour. Just wanted to state that it was unexpected to me.

Would there be a way to retain (basic?) autocompletion functionality in case people haven't added the dependency? Also I wonder if there would be a more prominent way to suggest that people add the dependency.

**Comment by jasongilman** [comment]
I think this is currently fixed on master with this pull request. https://github.com/jasongilman/proto-repl/pull/183 This hasn't been released yet.
