### ISSUE TITLE
Repl is crahing with java.lang.IllegalArgumentException: No such namespace: clojure.tools.namespace.repl

### ISSUE THREAD

**Issue by pradeepcheers** [jasongilman/proto-repl#194]
java.lang.IllegalArgumentException: No such namespace: clojure.tools.namespace.repl

**Comment by jasongilman** [comment]
Proto REPL tries to use this namespace when it starts up. I recommend including the Proto repl lib dependency (see https://clojars.org/proto-repl) which will allow you to use a lot of the features.

**Comment by jasongilman** [comment]
There are settings to disable refresh if you don't want to include it.

**Comment by pradeepcheers** [comment]
Thanks @jasongilman. Adding proto-repl dependency to my project.clj fixed the issue.
