### ISSUE TITLE
Unchecking Display Executed Code in REPL causes typed code to keep reappearing

### ISSUE THREAD

**Issue by seancorfield** [jasongilman/proto-repl#195]
Go into Settings and uncheck Display Executed Code in REPL. This does indeed suppress display of code sent from an editor but now if you type any code into the REPL directly and press shift-enter, after executing the code and displaying the result, the code you typed is redisplayed in the input field (and pressing shift-enter will re-execute it).

This means you need to select and delete each expression after execution.

This does not happen when Display Executed Code in REPL is checked.

**Comment by carocad** [comment]
I can confirm this bug in my proto-repl as well.

**Comment by jasongilman** [comment]
I pushed this fix with 1.4.10.

**Comment by seancorfield** [comment]
I can confirm this is now fixed, at least on Windows. I'll reconfirm on Mac tomorrow.
