### ISSUE TITLE
"Settings" button is missing in Atom 1.4.0-beta2

### ISSUE THREAD

**Issue by IshmaelYavitz** [jasongilman/proto-repl#20]
I installed proto-repl 0.7.0 in Atom 1.4.0-beta2.  There is no "Settings" button for the package.

I downgraded to Atom 1.2.4 and am seeing the button.

**Comment by IshmaelYavitz** [comment]
Forgot to mention: I'm using OS X 10.10.5.

**Comment by jasongilman** [comment]
Atom 1.4 is out and settings works correctly.
