### ISSUE TITLE
Two REPL in the same time in the same atom window

### ISSUE THREAD

**Issue by kwladyka** [jasongilman/proto-repl#200]
I have to run two REPL tab in the same window, because i use electron and need run frontend and backedn in the REPL at the same time. As i can see it is possible to run only one REPL at the same time? Am i right?

**Comment by jasongilman** [comment]
You can only run one REPL per atom window. But you should be able to have multiple windows open in order to have multiple REPLs.

**Comment by dotemacs** [comment]
I've just asked about this on Clojurians Slack in #protorepl. 

Is this still the case? Thanks

**Comment by kwladyka** [comment]
not active
