### ISSUE TITLE
REPL Toolbar vs atom-toolbar Package (aka hiding the toolbar)

### ISSUE THREAD

**Issue by tosh** [jasongilman/proto-repl#211]
In `proto-repl 1.4.10` I now see a toolbar above the REPL in addition to the toolbar that comes with `atom-toolbar` (see screenshot).

<img width="517" alt="screen shot 2016-12-20 at 6 56 57 pm" src="https://cloud.githubusercontent.com/assets/14825/21361867/2e976a58-c6e6-11e6-993f-d87fc0e2d13d.png">

I was looking for a way (through a command or in the settings of proto-repl) to hide the toolbar to get some more vertical screen real estate (I'm happy about every line I can save somehow) but did not find a way to get rid of it.

Is there a way to remove the toolbar that comes with `proto-repl` or maybe hide it by default if the `atom-toolbar` package is present?

**Comment by jasongilman** [comment]
The toolbar that is above the REPL is from Atom Ink. I don't see any settings in Atom Ink to remove that one. I would ask in the Atom Ink repo or file an issue to allow it to be hidden. In the meantime you could add this to your stylesheet to force it to be hidden. Just be warned that messing with styles could break other things potentially.

```less
// Hide Atom Ink Console Toolbar
.ink-toolbar .bar {
  height: 0;
}
```
