### ISSUE TITLE
java.lang.RuntimeException: Unable to resolve symbol: require

### ISSUE THREAD

**Issue by thoughtsofcode** [jasongilman/proto-repl#212]
I'm using boot-cljs-repl to start a remote repl. I am able to connect to the remote repl, start a ClojureScript repl using (adzerk.boot-cljs-repl/start-repl), and connect the browser to the Weasel server, however typing in the editor triggers the following error:

```
clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: Unable to resolve symbol: require in this context, compiling:(/tmp/boot.user7426829916556161843.clj:1:5)
             java.lang.RuntimeException: Unable to resolve symbol: require in this context
```

The error occurs on every keystroke in a .cljs file. I looked inside the temp file generated by boot and it's essentially just my built.boot file with some additional boilerplate. Any idea on what's triggering the error?

**Comment by jasongilman** [comment]
It must be the auto completion. You can disable that in the proto repl settings. You'll still get Atom's completions but not the full features completions.

**Comment by thoughtsofcode** [comment]
Thank you. You're right, unchecking the Enable Completions setting stopped the errors. I'd like to get the full features autocompletion working. Do you believe there's a configuration problem with my setup or is this just a current limitation of Proto REPL?

**Comment by jasongilman** [comment]
Proto REPL uses Compliment for completions which only supports Clojure right now and not ClojureScript. (That I know of)

https://github.com/alexander-yakushev/compliment

I haven't looked into how to do this yet for ClojureScript.

**Comment by thoughtsofcode** [comment]
Got it. Closing this issue then.
