### ISSUE TITLE
Can't find clojure.java.browse when using proto-repl

### ISSUE THREAD

**Issue by hswick** [jasongilman/proto-repl#213]
Get this error when I try to call (clojure.java.browse/browse-url "index.html")

ClassNotFoundException clojure.java.browse  java.net.URLClassLoader$1.run (URLClassLoader.java:372)

However, with no changes the function works when running in emacs.

**Comment by hswick** [comment]
I was able to get around this by using java.awt.Desktop's browse method. 

Still curious as to why clojure.java.browse can't be found when using proto-repl, but works when using cider in emacs. 

Gonna leave this open, for science...

**Comment by jasongilman** [comment]
You just need to require that namespace first to make it available like this:

```
(require 'clojure.java.browse)
(clojure.java.browse/browse-url "index.html")
```
