### ISSUE TITLE
Deprecated selector in `proto-repl/styles/proto-repl.less`

### ISSUE THREAD

**Issue by condur** [jasongilman/proto-repl#221]
In `proto-repl/styles/proto-repl.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `:host atom-text-editor .highlight.block-execution .region,
atom-text-editor atom-text-editor .highlight.block-execution .region,
atom-text-editor::shadow atom-text-editor .highlight.block-execution .region` => `:host atom-text-editor .highlight.block-execution .region,
atom-text-editor atom-text-editor .highlight.block-execution .region,
atom-text-editor.editor atom-text-editor .highlight.block-execution .region`

* `:host .highlights .block-execution .region,
atom-text-editor .highlights .block-execution .region,
atom-text-editor::shadow .highlights .block-execution .region` => `:host .highlights .block-execution .region,
atom-text-editor .highlights .block-execution .region,
atom-text-editor.editor .highlights .block-execution .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by phreed** [comment]
I think this means to change from...
```
:host, atom-text-editor, atom-text-editor::shadow {
  atom-text-editor .highlight.block-execution .region {
    position: absolute;
    pointer-events: none;
    z-index: -1;
  }

  .highlights {
    .block-execution .region {
      background-color: rgba(155, 149, 0, 0.6);
    }
  }
}
```
...to...
```
:host, atom-text-editor, atom-text-editor.editor {
  atom-text-editor .highlight.block-execution .region {
    position: absolute;
    pointer-events: none;
    z-index: -1;
  }

  .highlights {
    .block-execution .region {
      background-color: rgba(155, 149, 0, 0.6);
    }
  }
}
```

I am not sure what the 'syntax--' bit means.
