### ISSUE TITLE
Customizing Typeface and Font Size in Proto Repl

### ISSUE THREAD

**Issue by ercancem** [jasongilman/proto-repl#222]
How does one customize the typeface and font size in proto-repl console? (Windows 7.)

**Comment by jasongilman** [comment]
This console is from the Atom Ink package so I would ask in their [issues](https://github.com/JunoLab/atom-ink/issues). I think customizing the editor typeface and font size impacts the console. I'm not sure if it can be customized separately from the Editor typeface.

**Comment by ercancem** [comment]
That is my problem: console typeface and font size is not inherited from the editor. (It is initially inherited, but not after I customize the typeface and font size in the editor.)

**Comment by tabidots** [comment]
I dug into `ink` very quickly and came up with this snippet to add to your Atom stylesheet. Couldn't identify the exact child node in `.result`.

```css
ink-console > .items > .cell > .content > .result > * {
  // styles here
}
```
