### ISSUE TITLE
Changed code does not (always) take effect when file is reloaded

### ISSUE THREAD

**Issue by ercancem** [jasongilman/proto-repl#223]
The title is a bit cryptic.

Example: I define a function and a simple line to test it, for example:

```
(defn my-iterate [fn val]
  (cons val (lazy-seq (my-iterate fn (fn val)))))

(take 9 (my-iterate inc 5))
```

I start the proto-repl console from open project, load my file. Both execute code block from the file and invoking it from the console with some arguments work fine. Then I deliberately break the function. For example:

```
(defn my-iterate [fn val]
  (cons val (lazy-seq (my-iterateee fn (fn val)))))

(take 9 (my-iterate inc 5))
```

I save the file, reload the file. If I execute the function definition code block, I get an error as expected. But `(take 9 (my-iterate inc 5))` still works. I have to stop and reload the repl.

Am I doing something wrong? What is the correct procedure after editing the current file?

**Comment by moxaj** [comment]
When you first evaluate the function definition, the function is bound to the var `my-iterate`. When you evaluate the broken definition, it fails, and nothing changes, the same function is still bound to `my-iterate`, so `(take 9 (my-iterate inc 5))` still works. All of this is expected, I don't really see the issue?

**Comment by jasongilman** [comment]
Take a look at how this is setup. https://github.com/jasongilman/proto-repl-demo/blob/master/build.boot I'm not super familiar with boot but I think if you set it up this way it should work.

**Comment by jasongilman** [comment]
I accidentally closed this.

**Comment by jasongilman** [comment]
Even though I accidentally closed it a minute ago and then reopened it I think that it's not an issue. The comment from the previous user is correct. When you try to define a var in Clojure if the code doesn't compile the var won't be defined/redefined.
