### ISSUE TITLE
Deprecated selector in `proto-repl\styles\proto-repl.less`

### ISSUE THREAD

**Issue by alombide** [jasongilman/proto-repl#226]
In `proto-repl\styles\proto-repl.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `:host atom-text-editor .highlight.block-execution .region,
atom-text-editor atom-text-editor .highlight.block-execution .region,
atom-text-editor::shadow atom-text-editor .highlight.block-execution .region` => `:host atom-text-editor .highlight.block-execution .region,
atom-text-editor atom-text-editor .highlight.block-execution .region,
atom-text-editor.editor atom-text-editor .highlight.block-execution .region`

* `:host .highlights .block-execution .region,
atom-text-editor .highlights .block-execution .region,
atom-text-editor::shadow .highlights .block-execution .region` => `:host .highlights .block-execution .region,
atom-text-editor .highlights .block-execution .region,
atom-text-editor.editor .highlights .block-execution .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by mrattner** [comment]
This is a duplicate of #221. I think most people who noticed this (including me) did so because of the deprecation-cop package. So it's a very minor issue, but disconcerting to see the "!" in the status bar :)

**Comment by draeath** [comment]
Well, it's a minor issue *now.*

It'll cease to be minor when this little bit at the end happens: "Automatic translation of selectors will be removed in a few release cycles to minimize startup time."

**Comment by Quandrant** [comment]
Thank you-- I was just about to report this issue. It's a bit disconcerting to see the exclamation mark. :P

**Comment by jasongilman** [comment]
Duplicate of #221 which is fixed
