### ISSUE TITLE
Error with boot-clj

### ISSUE THREAD

**Issue by abhi18av** [jasongilman/proto-repl#227]
Hii @jasongilman 

This is an awesome project - thanks!!!

This has been working fine with `lein` but recently I've started to experiment with `boot` and as described in the readme I've updated my settings regarding `prefer lein`. 

I generated my folder structure using `boot -d seancorfield/boot-new new -t app -n music` but while using the `proto-repl` it throws an error 

```clojure
        clojure.lang.ExceptionInfo: No such task (dev)
    data: {:file
           "/var/folders/vt/9ywhthp94tz2b_23l97x9zcc0000gn/T/boot.user7941526324857306389.clj",
           :line 21}
java.lang.IllegalArgumentException: No such task (dev)
          boot.core/construct-tasks  core.clj:  905
                                ...                
    clojure.core/apply/invokeStatic  core.clj:  646
                 clojure.core/apply  core.clj:  641
                  boot.core/boot/fn  core.clj:  949
clojure.core/binding-conveyor-fn/fn  core.clj: 1938
                                ...                
REPL Closed

```

Could you please help me out?

**Comment by Invisible-Rabbit-Hunter** [comment]
add an empty task callde "dev" in your build.boot

**Comment by jasongilman** [comment]
Take a look at this https://github.com/jasongilman/proto-repl-demo/blob/master/build.boot I'm not super familiar with boot but if you setup your boot file this way then this should work.
