### ISSUE TITLE
Global goog constant leaking

### ISSUE THREAD

**Issue by mauricioszabo** [jasongilman/proto-repl#231]
Hello, I'm doing some experiments using ClojureScript for atom plugin development. The problem is that, when I'm developing, I want to use no optimizations, but proto-repl is leaking it's `goog` global variable.

I _think_ it would be easy to solve this - just compile everything that we need with the flags: 
`:optimizations :simple` and `:output-wrapper true`. I can do this if you think it's worth it. WDYT?

**Comment by jasongilman** [comment]
If you think that will work then I say go for it. I don't know as much about ClojureScript to know what problems this might cause.

**Comment by mauricioszabo** [comment]
I don't know it it helps, but I'm using proto-repl for about 8hrs a day, and haven't found a single issue until now.

Only thing I didn't test was *save values* and *charts*. Hope it helps!

**Comment by jasongilman** [comment]
That does help to know that. I'll still want to review it all and try it out. My work has been crazy lately but I'm still planning on merging this in soon.
