### ISSUE TITLE
allow enter to send command

### ISSUE THREAD

**Issue by mikeThurmond** [jasongilman/proto-repl#24]
similar to most repls used in clojure development

**Comment by jasongilman** [comment]
I've had multiple people mention this as an issue. Proto REPL not behaving like a normal REPL might be a barrier to adoption for some people. I like the approach (Cursive took for integrating the REPL)[https://cursive-ide.com/userguide/repl.html]. (See "Using the REPL" at that link). The REPL has two areas.  The top area is for display of executed code, print output, and results. The bottom of the REPL allows typing up a new form in an unrestricted manner. Newlines can be entered, backspaced, copy and paste are supported, etc. The user sends the form to the REPL using a special keystroke or by pressing enter at the end of a valid form. I'm currently looking into implementing it using this approach.

**Comment by jasongilman** [comment]
This feature has been implemented in 0.9.0.
