### ISSUE TITLE
loadCurrentFile sending string with unescaped backslashes to REPL

### ISSUE THREAD

**Issue by moxaj** [jasongilman/proto-repl#25]
`atom.workspace.getActiveTextEditor().getPath()` seems to return a string in which backslashes are unescaped, so the `(load-files ...)` fails. Adding `.replace(/\\/g,"\\\\")` seems to solve the problem (please note that my coffeescript knowledge is non-existent). I'm using win10 if it matters.

**Comment by jasongilman** [comment]
Thanks for the solution!. Released as version 0.8.3.
