### ISSUE TITLE
experiencing memory leaks with proto-repl and ink

### ISSUE THREAD

**Issue by mattly** [jasongilman/proto-repl#268]
This has been rather hard to pin down, but I've narrowed the problem down to either proto-repl or ink, with all other community packages disabled (which was not fun, because lisp editing without parinfer or paredit _sucks_). I'm seeing some rather severe memory leaks in Atom on Mac (over a GB of use in Activity Monitor after an hour, up to ten GB after six hours) of light eval use of smallish data structures when connected via nRepl. Just to eliminate any potential weird things in my setup, I moved my `.atom` away and started anew, and then set it up according to [Jason's guide](https://gist.github.com/jasongilman/d1f70507bed021b48625)

I'm not all that familiar with Atom or how to debug it, so if you've got any pointers or if there's more info I can provide, I'm happy to try and get that.

**Comment by jasongilman** [comment]
Atom has Chrome developer tools built in which can be used to debug performance or memory issues. You should be able to open the devtools through the menu and then look at memory usage. Use Profiles-> Take Heap snapshot. From there you can determine what's taking up the memory (ink, Proto REPL, or something else?). If you can grab a screenshot of memory usage that will help show the problem. Make sure that the screenshot includes enough details to see the objects using up memory.

**Comment by mattly** [comment]
Thanks! Ill be able to look at it more in-depth on Monday.

**Comment by mattly** [comment]
I haven't been able to reproduce the problem since – memory usage stays reasonable. I updated to Atom 1.19 today and memory usage seems even better. I'm going to close this, but if it comes up again, I'll know where to look. Thanks!
