### ISSUE TITLE
Run all tests should work without clojure.tools.namespace.repl

### ISSUE THREAD

**Issue by moxaj** [jasongilman/proto-repl#27]
The commands related to refreshing namespaces use functions from said namespace, but never seem to actually `require` it.

**Comment by jasongilman** [comment]
I'd expect this normally to be required in the user namespace, usually the dev/user.clj file like is done with the [proto repl demo project](https://github.com/jasongilman/proto-repl-demo). If you're not requiring it that's not a use case I had thought of. Is clojure.tools.namespace a dependency in your project? Have you setup a user.clj file like the [one in proto repl demo](https://github.com/jasongilman/proto-repl-demo/blob/master/dev/user.clj)?

**Comment by moxaj** [comment]
I don't have it in my deps, I don't think I have a use for them yet. I was actually trying to use the "Run all tests" functionality on the toolbar, which calls refreshNamespaces.

**Comment by jasongilman** [comment]
Ah ok. That should be able to work without clojure.tools.namespace. I can make change it to work without that. In the meantime you'll have a better user experience if you try to setup your project to use it.
