### ISSUE TITLE
Returned value is printed twice

### ISSUE THREAD

**Issue by evgenykochetkov** [jasongilman/proto-repl#33]
Mac OS 10.11.3, Atom 1.4.0, Leiningen 2.5.3, nREPL 0.2.10, proto-repl 0.11.0
When executing any code in REPL(sent from other editor or entered manually) returned value is printed twice, like this:

```
(println "hello")
hello
=>
nil
=>
nil
(str 123)
=>
"123"
=>
"123"
--------------------
```

**Comment by jasongilman** [comment]
That's odd. I'm not seeing that behavior with the same version of proto repl. Can you try restarting the Atom editor just in case there's some odd behavior from an update? It could be multiple callback handlers or something else. Does it always happen on a new REPL? Can you also try starting a REPL in a different leiningen project.

**Comment by evgenykochetkov** [comment]
I tried all kinds of restarting, starting with a fresh `.atom` folder, etc, and finally figured out the cause — cider-nrepl. Removing cider-nrepl from plugins in `.lein/profiles.clj` solved the problem.
