### ISSUE TITLE
Symbols in current ns cannot be resolved when sent to REPL

### ISSUE THREAD

**Issue by moxaj** [jasongilman/proto-repl#34]
My namespaces are refreshed and loaded, but I get "Unable to resolve symbol: ..." when sending code blocks to the REPL. Example: I have an ns `foo.core` with a function `bar`, sending `(bar)` throws an exception, sending `(foo.core/bar)` doesn't. This can be remedied by sending the definition of `bar` to the REPL, but shouldn't that have been done when loading the file?

**Comment by jasongilman** [comment]
Can you put the namespace definition from the top of your file as a comment here? I'm wondering if there's some difference that it doesn't handle when it tries to find the namespace of the current file. I think there may be an issue if the namespace isn't structured like this as the very first line of the file.

```
(ns some.namespace
  "docs"
  (:require ...))
```

**Comment by jasongilman** [comment]
Actually I've just determined this is a regression. I'll have a fix soon.
