### ISSUE TITLE
ArityException when evaluating anything in 0.12.1

### ISSUE THREAD

**Issue by IshmaelYavitz** [jasongilman/proto-repl#41]
I'm using proto-repl 0.12.1 in Atom 1.4.0.

I get an exception whenever I try to evaluate anything, using either execute-block or execute-selected-text, from either an editor tab or the REPL tab.

Examples:

```
*ns*
=> ArityException Wrong number of args (2) passed to: core/read-string  clojure.lang.AFn.throwArity (AFn.java:429)
(+ 1 2)
=> ArityException Wrong number of args (2) passed to: core/read-string  clojure.lang.AFn.throwArity (AFn.java:429)
```

**Comment by jasongilman** [comment]
Thanks for reporting this. It's a problem with different versions of Clojure. I'm using 1.8 now. The read-string must have added a new arity in 1.7 or 1.8. What version are you using?

**Comment by jasongilman** [comment]
I see that 1.7 added the two arity version. You must be using an earlier version. I'll see if I can make it work with earlier versions.

**Comment by IshmaelYavitz** [comment]
> You must be using an earlier version.

Ah, you are correct.  It's a compojure project created by `lein new compojure-app`, which by default uses Clojure 1.6.  I don't know why.  Maybe the template is just old.

I set the project to use 1.7.  I don't need to use 1.6.

**Comment by IshmaelYavitz** [comment]
Thanks for the fix!

**Comment by jasongilman** [comment]
It was good to figure out the limitation anyway. Proto REPL now supports 1.6 and greater.
