### ISSUE TITLE
Error while trying to upgrade the version to proto-repl@0.12.2

### ISSUE THREAD

**Issue by pradeepcheers** [jasongilman/proto-repl#42]
npm ERR! git fetch -a origin (git://github.com/rksm/node-nrepl-client.git) fatal: read error: Operation timed out
npm ERR! Darwin 15.2.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/Pradeep/.atom/.apm/.apmrc" "--userconfig" "/Users/Pradeep/.atom/.apmrc" "install" "/private/var/folders/sg/pl30nx_s5qbbcqnb04xtxpqw0000gn/T/d-116026-27545-1ujnr5a/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: fatal: read error: Operation timed out
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/sg/pl30nx_s5qbbcqnb04xtxpqw0000gn/T/apm-install-dir-116026-27545-1fzzm38/npm-debug.log

**Comment by jasongilman** [comment]
It looks like there may have been a temporary problem downloading the node-nrepl client from github. Can you try upgrading it again?

**Comment by pradeepcheers** [comment]
Thanks @jasongilman, I managed to install the plugin. For some reason I cannot install from my work network.
