### ISSUE TITLE
[QUESTION] remote repl?

### ISSUE THREAD

**Issue by johnryan** [jasongilman/proto-repl#46]
Is there any way to set up a connection to a remote repl?

**Comment by martinklepsch** [comment]
@johnryan I guess this would be possible as soon as there is the possibility of connecting to an existing nREPL server as tracked in #17

**Comment by jasongilman** [comment]
There's currently a pull request open to add this feature. I just need to review it, test, merge it, and then publish an update. That should all be done in the next couple days.

**Comment by johnryan** [comment]
awesome thanks.
