### ISSUE TITLE
Project detection should be smarter

### ISSUE THREAD

**Issue by j-em** [jasongilman/proto-repl#47]
![proto-repl-bug](https://cloud.githubusercontent.com/assets/943725/12629878/bb2a1e38-c517-11e5-8f61-9988763fd987.png)

I have a lein project structured the most known way: `project.clj` at the root of the project with namespaces organized like this: `src/foo/moo.clj` `src/foo/poo.clj`, etc...

When I try hitting `C-, shift+L` while inside project.clj - it picks up the project correctly.
If I try doing the same thing while I'm visiting `src/foo/moo.clj`, its assuming I'm not inside a project and its defaulting to a template project.

After skimming through the code, it looks like proto-repl is relying on `atom.project.getPaths()` to get the root of the current project which seem to not return the correct thing.

EDIT: Okay maybe I misunderstood the way projects are implemented in atom - if you open the root project manually within atom, its working correctly.
If I try launching `atom myfile.clj`\- it doesn't see my project at all. :-(

I expected a behavior similar to emacs and cider. I find the current behavior confusing. Perhaps this is outside of the scope of proto-repl ?

**Comment by jasongilman** [comment]
Thanks for filing this issue. I've thought about whether or not this is something that Proto REPL should be  able to handle. I wasn't sure if it made sense for it to be searching above the current directory for a project.clj file. How far up should it search? I think you're right though that it would be a nicer experience if it could do this. I'm going to think about this some more but I'm leaning towards closing it now. Do you have any information on how this works in cider?

**Comment by j-em** [comment]
Fortunately I had a look recently at this part of cider's code. Cider normally delegates these kind of project-related tasks to someone else.

I know in emacs we got `projectile` as a very high-level project library - it has multiple ways of determining if something is a project or not. Usually its implemented around vcs folders, so if you have a `.git` folder at the root of another folder - it's considered a project.

Back to cider, its using this function from clojure-mode to determine the root of a project https://github.com/clojure-emacs/clojure-mode/blob/cabd566d87c1ef03e104d829557f5acc458a7ba3/clojure-mode.el#L1300

From what I understand , they're searching for a project.clj file or the boot equivalent to establish the root of a project.

**Comment by jasongilman** [comment]
There were a few small changes I had to make to fix issues with REPL starting. It's working now. It will be in the next release of Proto REPL.
