### ISSUE TITLE
proto-repl should allow you to insert a "break" in repl output

### ISSUE THREAD

**Issue by ccuadrado** [jasongilman/proto-repl#48]
For example if I'm running a lot of blocks where various logging statements are printed like: 
foo.bar.baz.services/some-function took 10 ms 
I should be able to insert a marker/anchor (or even just ************_!!!!!!!!!!!**_****************) in the code, something clearly visible that denotes the execution between blocks, bound to some key-function.

In SublimeText2 it had a feature where I could hit return a bunch of times and it would move all the output up a few blank lines so I could identify the beginning of something I wanted to do next.

**Comment by jasongilman** [comment]
This is an example of something that you can add to your own setup using the powerful extensibility features of Atom and Proto REPL. Proto REPL adds a global variable that lets you reference it from inside custom handlers in Atom. Add something like this to Atom's init.coffee

``` CoffeeScript
atom.commands.add 'atom-text-editor', 'custom-proto-repl:insert-break', ->
  protoRepl.appendText("\n;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\n\n")
```

That adds a custom handler called `custom-proto-repl:insert-break`. After you do that restart atom or "Reload" via the View menu to reload your init script. Now when Proto REPL is running the text will get appended if you bring up the command palette (cmd-alt-p) and select that command. You can also add your own keybinding. 

Under `'.platform-darwin .workspace atom-text-editor[data-grammar~="clojure"]':` insert something like this:

``` CSON
'cmd-shift-i': 'custom-proto-repl:insert-break'
```
