### ISSUE TITLE
Key Bindings for Linux (and Windows)

### ISSUE THREAD

**Issue by phreed** [jasongilman/proto-repl#5]
Use of 'cmd' is limited to osx.
A default set of bindings for Linux (and Windows) would be nice.

**Comment by jasongilman** [comment]
I just pushed an update of Proto REPL with new keybindings that should work for Linux, Windows, and OSX. Try the newest version (0.3.0) and take a look at the keybinding documentation https://github.com/jasongilman/proto-repl#keybindings-and-events

**Comment by phreed** [comment]
looks good.
Some of the README.md still mentions the 'cmd'.
