### ISSUE TITLE
clojure.tools.namespace.repl not available

### ISSUE THREAD

**Issue by saulshanabrook** [jasongilman/proto-repl#52]
I have been getting this error:

```
clojure.tools.namespace.repl not available. Add as a dependency and require in user.clj.
```

I tried changing my `~/.lein/profiles.clj` to:

``` clojure
{:user {:plugins [[lein-pprint "1.1.1"]]}
 :repl {:dependencies [[org.clojure/tools.namespace "0.2.11"]]}}
```

and my `~/.lein/user.clj` to:

``` clojure
(ns "user")

(require 'clojure.tools.namespace.repl)
```

But the only thing that worked was adding

``` clojure
  :repl-options {:init (require 'clojure.tools.namespace.repl)}
```

To my `./project.clj` file.

What is the recommended way to address this issue?

**Comment by jasongilman** [comment]
You should define your user namespace like this:

```
(ns user
  (:require [clojure.tools.namespace.repl :as tnr]))
```

That's from the [Proto REPL demo project](https://github.com/jasongilman/proto-repl-demo/blob/master/dev/user.clj). Take a look at that project for how it sets up things.

**Comment by saulshanabrook** [comment]
So that can go in the `~/.lein/user.clj` file?

**Comment by jasongilman** [comment]
It goes in your Clojure project under `dev/user.clj`

**Comment by saulshanabrook** [comment]
Is it possible to make this work for all projects?
