### ISSUE TITLE
Return value is printed out twice in the REPL

### ISSUE THREAD

**Issue by asampal** [jasongilman/proto-repl#57]
When I evaluate `(first '(4 5 3))` using the ctrl-, b binding in the REPL (this is without Ink installed), I get:

```
=> 4
=> 4
--------------------
(first '(4 5 3))
```

Why is the result printed out twice? For that matter, why is the original expression repeated? Is the presumption that you'd want to modify it and re-evaluate it? Also, the re-printing of the evaluated expression doesn't happen if the evaluation is done on an expression in a regular editor - should output not be consistent across the REPL and editor invocations? Edit: just noticed that if the evaluation is invoked in the REPL using shift-enter, the original expression is not repeated (but the output is still doubled).

**Comment by jasongilman** [comment]
This doesn't happen normally. Someone reported this before as #33.  It was caused by cider-nrepl in their profiles.clj

> I tried all kinds of restarting, starting with a fresh .atom folder, etc, and finally figured out the cause — cider-nrepl. Removing cider-nrepl from plugins in .lein/profiles.clj solved the problem.

Can you see if you have a similar issue?

I tried proto repl with no ink enabled and evaluated `(first '(1 2 3))` and I get the expected output in the repl

``` Clojure
(first '(1 2 3))
=>
1
--------------------
```

**Comment by asampal** [comment]
You're right, removing cider-nrepl fixes this problem, but I'd still like to be able to use Emacs/Cider along with Atom so I'd like to keep it there. Maybe you could ask @Malabarba (Artur Malabarba, the author) in the [gitter room](https://gitter.im/clojure-emacs/cider) or on [slack](https://clojurians.slack.com/messages/cider/details) where he hangs out what could be done to make things work despite cider-nrepl being present. 

BTW, you might want to consider creating some rooms for proto-repl in one or both of those places. They're pretty active for Clojure.

**Comment by Malabarba** [comment]
While I'm happy to help, let me clarify I'm a contributor (not _the_ aurhor) and we should also ping @bbatsov (the maintainer). 

As for the actual problem, I'm sad to say nothing comes to mind. Maybe with more information about how proto-repl works I'll be able to help, but I'm not aware of any cider-nrepl middleware that affects return values. 

Cider-nrepl does carry some middleware that causes additional responses to be sent (such as the state_tracker).

**Comment by bbatsov** [comment]
I'm guessing proto-repl has some way to inspect the messages exchanged by it and the nREPL server - I'd suggest showing us those messages, so we can help you out.

**Comment by bbatsov** [comment]
Looking at the installation instructions it seems to me proto-repl doesn't use any additional middleware. Is this correct?

**Comment by jasongilman** [comment]
Thanks for helping.  Proto REPL doesn't use any additional middleware. It uses https://github.com/rksm/node-nrepl-client for connecting to nREPL. I printed out the messages returned after requesting `(+ 1 1)`.

(GUIDs truncated)

```
{"id":"0048FDA8","ns":"user","session":"acf79b4f","value":"2"}
{"id":"0048FDA8","session":"acf79b4f","status":["done"]}
```

Then I tried using Proto REPL after installing cider-nrepl and the messages looked like this:

(GUIDS truncated)

```
{"id":"46BF16F1","ns":"user","session":"0c868cc4","value":"2"}
{"id":"46BF16F1","ns":"user","session":"0c868cc4","value":"2"}
{"id":"46BF16F1","session":"0c868cc4","status":["done"]}
{"id":"46BF16F1","session":"0c868cc4","status":["done"]}
```

In addition two other messages were returned with "state" status. 

I tried debugging node-nrepl-client at a lower level and it looks like only one message is being returned so I'm not sure why I'm seeing the doubling. I can't tell if it's a bug in node-nrepl-client or something else. I wonder if there's a way to tell nREPL to avoid using a middleware.

**Comment by jasongilman** [comment]
Here's the logging inside node-nrepl-client when using cider-nrepl

```
nREPL message chunk received (3128 bytes)
nrepl message received (113 bytes, {
  id: 'E506CF61-5B0D-46CF-865F-6C73867CF117',
  ns: 'user',
  session: 'd92e5ef8-5ec8-43ec-8363-ca8176725d6a',
  value: '2'
})

nrepl message received (109 bytes, {
id: 'E506CF61-5B0D-46CF-865F-6C73867CF117',
  session: 'd92e5ef8-5ec8-43ec-8363-ca8176725d6a',
  status: [ 'done' ]
})

nrepl message received (2903 bytes, {
  changed-namespaces: Dict {
    'clojure.string': [Object],
    'proto-repl-demo.conditional': [Object],
    'proto-repl-demo.demo': [Object],
    'proto-repl-demo.demo-test': [Object] },
  id: 'E506CF61-5B0D-46CF-865F-6C73867CF117',
  repl-type: 'clj',
  session: 'd92e5ef8-5ec8-43ec-8363-ca8176725d6a',
  status: [ 'state' ]
})
```

There's no doubling of messages there but I see double messages delivered over their API to my JavaScript callback.

**Comment by jasongilman** [comment]
I've traced this down to a single problem. There's a callback being made twice when executing `*clojure-version*`. This double callback was then adding two sets of handlers for printing out nREPL messages. I added some temporary code to handle that and all other messages returned so far only come back once.

At this point it looks like the problem is almost certainly not with cider-nrepl. I need to do some more investigation but in any case I'll have a fix for Proto REPL so that if the cider-nrepl middleware is used Proto REPL will still behave normally.

**Comment by bbatsov** [comment]
Great! Btw, you should investigate the functionality offered by `cider-nrepl` - it's really not Emacs specific and it can really help you add extra functionality to `proto-repl` easily. We've learned from experience that there's a limit to what you can do by relying simply on nREPL's `eval`. :-)

**Comment by Malabarba** [comment]
And if you do decide to use it, don't hesitate to ask questions on the repo or on gitter. 

Anyway, I'm glad you've found the issue. 👍
