### ISSUE TITLE
With Ink installed, editor evaluation should not appear in the REPL

### ISSUE THREAD

**Issue by asampal** [jasongilman/proto-repl#58]
When inline evaluation is enabled through Ink, I would expect the result to be only inline in the editor, not also in the REPL (unless done through a binding for an action that specifically sends the evaluation result to the REPL).

**Comment by jasongilman** [comment]
That's a good idea but I'm not sure about this yet. The inline display is good in some scenarios but in others where the result is a large nested structure I still like to be able to see the whole thing printed. The inline display currently requires clicking around with the mouse to view the whole thing. If you automatically show the entire structure then you have large panes overtop of your code. I think what your suggesting could be done eventually but it's a bit too early now. This is a good goal though. I may add an option to not display the result in the REPL but leave it checked by default.

I just filed an issue, https://github.com/JunoLab/atom-ink/issues/35, with Atom Ink to see if keyboard navigation could be added. That would be helpful in getting to the point where display in the REPL is no longer required.

**Comment by jasongilman** [comment]
I'm closing this issue for now. It may be something we can get rid of in the future though.
