### ISSUE TITLE
Ctrl+C in the repl

### ISSUE THREAD

**Issue by ioRekz** [jasongilman/proto-repl#6]
Hello, I'm following this tutorial
https://github.com/pedestal/pedestal/blob/master/guides/documentation/hello-world-service.md

trying to get good repl experience but after starting the serv, I can't ctrl+c to get back to the prompt.
Any idea how to achieve this ?

**Comment by phreed** [comment]
I am guessing that you are looking for  an update to the README.md?
The behavior of ctrl+c that you mention is presumes you are working from the console.
The prompt is an artifact of the console, so there is nothing (meaning a console) to go back to.
Atom and proto-repl are not the console, they send strings to the REPL and post the results to the 'Clojure REPL' pane.
The sending of strings is controlled in various ways such as the ctrl+, b which sends a block of text.

**Comment by roryokane** [comment]
I think @ioRekz’s situation is more complicated than that. From the document he linked, it looks like the prompt he is talking about is not the shell prompt, but really the Clojure REPL prompt.

```
      +----- ^C ------+     +-------- ^C --------+
      V               |     V                    |
+------------+     +--+--------+      +----------+-----+
|shell prompt|     |REPL prompt|      |Jetty server log|
+-----+------+     +--------+--+      +----------------+
      |               ^     |                    ^
      +-- lein repl --+     +-- (server/start) --+
```

When he presses Ctrl+C, he isn’t trying to leave the REPL. He’s trying to leave a Jetty server log view that he started from the REPL. Basically, he’s trying to send the interrupt signal to a Clojure program that he started from the REPL.

This is a similar problem to letting the user type input for stdin read by a Clojure program. Currently, Proto REPL doesn’t handle that case either. If you send `(read-line)` to the REPL, you can’t directly type in user input, so nothing happens. But the next line of code you send to the REPL is interpreted as the input instead, which the user probably wasn’t expecting.

**Comment by ioRekz** [comment]
You got it right, I wish I can be as clear as you are, thanks.

**Comment by jasongilman** [comment]
I've had a couple other people ask about making the REPL in Proto REPL behave more like a regular REPL. I'm going to look into ways to do that.

**Comment by jasongilman** [comment]
This has been fixed by changing Proto REPL to use nREPL as the backend. You can send an interrupt to the REPL by pressing ctrl-shift-c. This will be part of Proto REPL 0.6.0.
