### ISSUE TITLE
Cannot start new REPL after closing one 

### ISSUE THREAD

**Issue by tgoff** [jasongilman/proto-repl#62]
If I close the REPL with the buffer 'x' button, I cannot re open it without restarting Atom

**Comment by jefffriesen** [comment]
I get the same behavior

**Comment by MJB47** [comment]
I get the same thing as well. Sometimes there are still some java processes running as well (always multiples of 2)

this seems inconsistent though

**Comment by jasongilman** [comment]
The only way I could reproduce this was if I closed the REPL while it was still starting up the Clojure process. If I waited until it opened all the way it would work. I fixed the issue though so you can close the tab and then immediately open a new REPL. The only problem is that this leaves a Java process running. I couldn't figure out a way around that yet. I send the the SIGKILL to the child process but it doesn't actually kill it.
