### ISSUE TITLE
Can't find lein

### ISSUE THREAD

**Issue by cap10morgan** [jasongilman/proto-repl#7]
On my system (Mac OS X 10.11.1, Atom 1.2.0):

`which lein` => `/usr/local/bin/lein`

In proto-repl settings:

<img width="510" alt="screen shot 2015-11-17 at 8 44 47 am" src="https://cloud.githubusercontent.com/assets/59748/11216256/8132225e-8d07-11e5-8f47-f44872bb9448.png">

But I when I start it:

<img width="535" alt="screen shot 2015-11-17 at 8 45 31 am" src="https://cloud.githubusercontent.com/assets/59748/11216282/9b0c6810-8d07-11e5-90d8-b65545e0d902.png">

**Comment by jasongilman** [comment]
I just pushed a new version (0.3.1) that may address this. Please try it and let me know if it resolves the issue.

**Comment by cap10morgan** [comment]
Yeah, that seems to have fixed it. Thanks!
