### ISSUE TITLE
in-ns?

### ISSUE THREAD

**Issue by matthias-margush** [jasongilman/proto-repl#75]
I noticed that in-ns doesn't affect clojure.core/_ns_. Is this expected?

```
(in-ns 'foo)
=>
[clojure.lang.Namespace 497383057 "foo"]
clojure.core/*ns*
=>
[clojure.lang.Namespace 606485950 "user"]
--------------------
```

**Comment by jasongilman** [comment]
It's expected based on the current implementation. Proto REPL always uses the user namespace currently. It seems like some people like to work in the REPL by setting the current namespace. I'll look into how to determine if code has changed the current namespace.
