### ISSUE TITLE
Problem with refresh or repl start

### ISSUE THREAD

**Issue by McNullty** [jasongilman/proto-repl#78]
When starting new REPL I get this message:

nREPL server started on port 59116 on host 127.0.0.1 - nrepl://127.0.0.1:59116
Refreshing code...
Refresh failed: FileNotFoundException Could not locate user__init.class or user.clj on classpath.  clojure.lang.RT.load (RT.java:456)

**Comment by McNullty** [comment]
When following proto-repl-demo error was not showing and refresh is working, must be some configuration problem.

**Comment by jasongilman** [comment]
im going to reopen this. Proto REPL should work without a user.clj file.

**Comment by evgenykochetkov** [comment]
I am encountering the same issue in a fresh project created with `lein new`.

**Comment by jasongilman** [comment]
I'm busy with some other things right now. If someone wants to try to fix this here's some advice
- The relevant code is here: https://github.com/jasongilman/proto-repl/blob/master/lib/proto-repl.coffee#L446
- If there's a user namespace and a reset function that should be used.
- If there's no reset function it should fallback to `(clojure.tools.namespace.repl/refresh)`
- If the user namespace isn't defined at all it should still fallback to that as well.
- If `clojure.tools.namespace.repl` isnt' available a helpful error message should be displayed. 

I started writing the error message but can't continue with this issue right now. The goal is excellent error messages (and I currently fall short of that).
Suggested error message:
"No user namespace or clojure.tools.namespace available to allow refreshing code. You can disable refresh on startup via the Protol REPL settings. However, refreshing is a useful feature. See this https://github.com/clojure/tools.namespace#reloading-code-motivation for why you should use it. See https://github.com/jasongilman/proto-repl-demo and the dev/user.clj for how to set it up."

**Comment by bernik** [comment]
there is one more bug on https://github.com/jasongilman/proto-repl/blob/master/lib/proto-repl.coffee#L456
you are sending 'user/reset after tnr.refresh but this symbol doesn't exists because it wasn't found three lines above

**Comment by olegakbarov** [comment]
Got similar(?) problem with boot.

```
[1;31mjava.io.FileNotFoundException[m: [31mCould not locate compliment/core__init.class or compliment/core.clj on classpath.[m
```

Any advice?

**Comment by jasongilman** [comment]
I think you're missing the Proto REPL library in your dependencies. Add a dependency to this https://clojars.org/proto-repl
