### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by roryokane** [jasongilman/proto-repl#8]
This package assumes you are already within a Clojure project, and fails to catch the resulting error if you try to use it outside of one.

Steps to reproduce:
1. Open a new window from the file menu. A blank tab named “untitled” will be selected.
2. Change the language to Clojure by clicking “Plain Text” at the bottom right and selecting “Clojure”.
3. Choose the menu item Packages → proto-repl → Start REPL.

You should catch the thrown error and display a friendlier error message somewhere. The error dialog should be non-modal – perhaps you could write the error inside the opened REPL window and highlight it in red. It would say that the current file must be within a Leiningen project, or the current project folder must be a Leiningen project, whatever the actual requirement is.

Ideally, if you try to start a REPL for an unsaved file, or a saved file that is not in a project, Proto REPL would automatically create a Clojure project in a temp directory for you, and start that project’s REPL. You should be able to send the REPL expressions to evaluate from the unsaved file. Proto REPL should avoid leaving multiple copies of temp projects around if you do that many times. That could be a long-term goal.

**Atom Version**: 1.2.3
**System**: Mac OS X 10.9.5
**Thrown From**: [proto-repl](https://github.com/jasongilman/proto-repl) package, v0.3.1
### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:8

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.resolve (path.js:424:5)
    at new ReplTextEditor (/Users/roryokane/.atom/packages/proto-repl/lib/repl-text-editor.coffee:75:31)
    at Object.module.exports.ProtoRepl.toggle (/Users/roryokane/.atom/packages/proto-repl/lib/proto-repl.coffee:116:29)
    at atom-workspace.subscriptions.add.atom.commands.add.proto-repl:toggle (/Users/roryokane/.atom/packages/proto-repl/lib/proto-repl.coffee:35:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:987:28)
    at emitOne (events.js:77:13)
```
### Commands

```
     -0:34.7.0 grammar-selector:show (atom-text-editor.editor.vim-mode.normal-mode)
     -0:32.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:28.1.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  4x -0:27.1.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:25 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:24.2.0 parinfer:toggleMode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:23.5.0 vim-mode:move-left (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:23.3.0 vim-mode:move-right (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:23.2.0 vim-mode:delete-right (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -0:23 vim-mode:move-left (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:22.4.0 vim-mode:move-right (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:22.3.0 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:21.6.0 vim-mode:substitute (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:19.5.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:14.9.0 proto-repl:toggle (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "open-on-github",
      "linter",
      "bracket-matcher"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Parinfer, v0.8.1
minimap, v4.16.1
proto-repl, v0.3.1
vim-mode, v0.63.0

# Dev
vim-mode, v0.11.1
```

**Comment by jasongilman** [comment]
Thanks for leaving such a detailed error report with suggestions. This was a great idea. I packaged a default Leiningen project with Proto REPL to avoid having to create a new one in a temp directory. Now Proto REPL can start a REPL in any new Atom window.
