### ISSUE TITLE
Sorted sets are sometimes printed as unsorted sets

### ISSUE THREAD

**Issue by moxaj** [jasongilman/proto-repl#81]
Evaluating `(into (sorted-set) [64 37 10 -18 52 21 54 88 -102])` prints `#{64 37 10 -18 52 21 54 88 -102}`. However, evaluating `(into (sorted-set) [64 37 10 -18])` prints `#{-18 10 37 64}`. Seems weird.

**Comment by jasongilman** [comment]
This is caused by the pretty printing issue as described in #77. You can disable the auto pretty printing in the Proto REPL settings to work around it.

Auto pretty printing turned off

```
(into (sorted-set) [64 37 10 -18 52 21 54 88 -102])
user=> #{-102 -18 10 21 37 52 54 64 88}
```

Auto pretty printing turned on

```
(into (sorted-set) [64 37 10 -18 52 21 54 88 -102])
user=>
#{64 37 10 -18 52 21 54 88 -102}
```
