### ISSUE TITLE
Proto REPL does not parse namespace declarations correctly

### ISSUE THREAD

**Issue by jasongilman** [jasongilman/proto-repl#87]
Proto REPL will not parse a namespace declaration that isn't written in the form `(ns some.name ...)`. If metadata like `(ns ^{:author "Jane Smith" :doc "Does something interesting" some.name ...)` then it won't find the name. Proto REPL should be updated to use clojure.tools.namespace which can parse these. This should be integrated into proto-repl-client-cljs.

**Comment by mauricioszabo** [comment]
Isn't this a duplicate of https://github.com/jasongilman/proto-repl/issues/152? If so, we already fixed it, right?

**Comment by jasongilman** [comment]
That's correct. Thanks
