### ISSUE TITLE
optionally include other autocomplete providers

### ISSUE THREAD

**Issue by trival** [jasongilman/proto-repl#89]
Hi,

I started using proto-repl for a ClojureScript figweel project, and connect to a external repl by its port.
Everything works great so far, just the autocompletion results in ClojureScript files are incomplete and miss symbols and namespaces. 

The configuration for the completion-provider sets `excludeLowerPriority: true`

By setting this locally to `false` i get a pretty nice autocomplete experience as the default provider recognises most of the symbols in the project.

Do you think making an option to include other providers would make sense? Or is there another way to improve autocompletion for ClojureScript?

PS: Thanks a lot for this package! I am full of joy writing my favourite language in my favourite editor.

**Comment by jasongilman** [comment]
There might be a way to improve completions in ClojureScript in the future. I've gone with your suggestion for now. This has been released with 1.1.7. Thanks for the suggestion!
