### ISSUE TITLE
Up/down history multiple lines scroll to bottom

### ISSUE THREAD

**Issue by robahl** [jasongilman/proto-repl#93]
When using the command history (up/down) and it shows a multiline form you only see the first line. Is this intended or could it automatically scroll to bottom to show all the lines?

**Comment by jasongilman** [comment]
You should see the entire form. There's an proto repl option that's on be default to automatically scroll to the bottom when new content is written. Do you have that off?

**Comment by jasongilman** [comment]
I don't think this is an issue. Let me know if this is still a problem.
