### ISSUE TITLE
Documentation is printed in REPL as single string

### ISSUE THREAD

**Issue by bytebutt** [jasongilman/proto-repl#94]
When documentation is printed in the REPL using `Ctrl-, d`, the documentation is printed as a single string. The auto pretty-print setting does not affect the behavior of this problem, nor does doing a manual pretty-print. Printing code with `Ctrl-, c` works as expected, and manually calling `clojure.repl/doc` in the REPL works as expected.

I'm not sure if this is a Proto REPL issue or something misconfigured in my environment. I didn't always have this problem, but I'm also not sure when this started because I updated Atom and Proto REPL several times without working on any Clojure code. I'm happy to provide any additional information you might need.

**Screenshot of Problem**
![print_doc](https://cloud.githubusercontent.com/assets/1648928/14549262/4a33ff52-028c-11e6-8e84-0caaea1d465a.png)

**Current Environment**
- Arch Linux
- Atom 1.7.1
- Proto REPL 1.1.8

**Comment by bytebutt** [comment]
This seems to be related to the call to `with-out-str` in proto-repl.coffee [line 570](https://github.com/jasongilman/proto-repl/blob/master/lib/proto-repl.coffee#L570). I've tested removing the call to `with-out-str` in dev mode and can confirm that printing documentation begins working as expected.

While removing the call fixes my observed issue, I don't know the code well enough to know if simply yanking it would cause other problems.

**Comment by jasongilman** [comment]
Fixed this in latest commit.
