### ISSUE TITLE
Trailing spaces in REPL

### ISSUE THREAD

**Issue by nicorikken** [jasongilman/proto-repl#96]
To be fair, it is a tiny detail, but the REPL window has trailing spaces in both the static text and the dynamic text (compiling statement). I have a trailing space highlighter turned on to catch such errors in code and documents, and for that reason I noticed it in the REPL as well.
![screen shot 2016-04-22 at 16 48 26](https://cloud.githubusercontent.com/assets/7458098/14745150/36a80482-08aa-11e6-8044-a724f325baeb.png)

**Comment by nicorikken** [comment]
I just created PR #97 to resolve the trailing whitespace in the static text. I'll have to look into the dynamic text some other time.

**Comment by nicorikken** [comment]
It seems the non-static whitespace originates from the `debug-prn`: https://github.com/jasongilman/proto-repl/blob/685c09cdc0579aa44ade8bb068d1d78c947a2895/lib/proto_repl/cljs/compiler.cljc#L1280
It seems that that particular whitespace originates from string manipulation, deeper down. Maybe I'll dive deeper later on. For now I'm happy to have found one of the two issues.

**Comment by jasongilman** [comment]
I think since this originates within clojure or clojurescript itself there's not much I can do with the other whitespace. I'm going to close this issue.
