### ISSUE TITLE
Inline display not scrolling when it overlaps bottom of current page

### ISSUE THREAD

**Issue by Misophistful** [jasongilman/proto-repl#99]
The scroll bars don't appear, and the panel can't be scrolled in any direction, even though there is additional data to show.

<img width="1280" alt="screen shot 2016-05-04 at 10 58 24" src="https://cloud.githubusercontent.com/assets/5363984/15009539/2c235aac-11e7-11e6-99a3-5d6821bd3a98.png">

**Comment by jasongilman** [comment]
I think this is really a bug with Atom Ink since this is using their inline display. I've filed an issue there to track it.

**Comment by Misophistful** [comment]
Thanks for reporting the bug in the right place. I should have realised that it was probably an Ink issue.

By the way, thanks for your amazing work on proto-repl. It's shaping up to be an excellent way to write Clojure code. 😄
